source 'http://rubygems.org'

gem 'rails', '3.1.1'
gem 'aws-s3'
gem 'aws-sdk'
gem 'devise', :git => 'https://github.com/plataformatec/devise.git'

gem "paperclip", "~> 3.0"

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

group :production do
  gem "pg"
  gem 'simple_form'
end

group :development, :test do
  gem "sqlite3"
  gem 'simple_form'
  gem 'rspec-rails'
  gem 'spork-rails' 
  gem 'spork'
  gem 'ZenTest'
  gem 'autotest-rails'
  gem 'autotest-growl'
  
  gem 'factory_girl_rails'
end

gem 'json'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
